service: canary-aws-ping

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  
  environment:
    APP_VERSION: ${self:custom.version}
    SERVERLESS_STAGE: ${self:provider.stage}
    LOG_LEVEL: ${opt:log-level, 'info'}

  deploymentBucket:
    name: canary-aws-ping-deployments-${aws:accountId}

custom:
  version: ${file(package.json):version}

functions:
  ping:
    handler: src/handlers/ping.handler
    description: 'Ping service with Node.js version response'
    timeout: 10
    memorySize: 128
    
    # CRITICAL: Use qualifier to make API Gateway call the alias
    events:
      - http:
          path: ping
          method: get
          cors: true
          # This makes API Gateway call the Live alias instead of $LATEST
          qualifier: Live

resources:
  Resources:
    # Lambda Version (published version for stable releases)
    PingLambdaVersion:
      Type: AWS::Lambda::Version
      Properties:
        FunctionName: !Ref PingLambdaFunction
        Description: 'Version for canary deployment'
        
    # Live Alias with weighted routing capability
    PingLambdaAliasLive:
      Type: AWS::Lambda::Alias
      Properties:
        FunctionName: !Ref PingLambdaFunction
        # Point to a specific version (not $LATEST)
        FunctionVersion: !GetAtt PingLambdaVersion.Version
        Name: Live
        Description: 'Production alias with canary routing support'
        # RoutingConfig will be updated by scripts for canary deployment

    # CloudWatch Alarms for monitoring
    PingErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: !Sub '${self:service}-${self:provider.stage}-ping-errors'
        AlarmDescription: Lambda function errors
        ComparisonOperator: GreaterThanThreshold
        EvaluationPeriods: 2
        MetricName: Errors
        Namespace: AWS/Lambda
        Period: 60
        Statistic: Sum
        Threshold: 0
        Dimensions:
          - Name: FunctionName
            Value: !Ref PingLambdaFunction

    PingLatencyAlarm:
      Type: AWS::CloudWatch::Alarm  
      Properties:
        AlarmName: !Sub '${self:service}-${self:provider.stage}-ping-latency'
        AlarmDescription: Lambda function latency
        ComparisonOperator: GreaterThanThreshold
        EvaluationPeriods: 2
        MetricName: Duration
        Namespace: AWS/Lambda
        Period: 60
        Statistic: Average
        Threshold: 1000
        Dimensions:
          - Name: FunctionName
            Value: !Ref PingLambdaFunction