service: canary-aws-ping

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  
  environment:
    APP_VERSION: ${self:custom.version}
    SERVERLESS_STAGE: ${self:provider.stage}
    LOG_LEVEL: ${opt:log-level, 'info'}

  deploymentBucket:
    name: canary-aws-ping-deployments-${aws:accountId}

custom:
  version: ${file(package.json):version}

functions:
  ping:
    handler: src/handlers/ping.handler
    description: 'Ping service with Node.js version response'
    timeout: 10
    memorySize: 128
    
    # Enable versioning for canary deployments
    versioning: true
    
    events:
      - http:
          path: ping
          method: get
          cors: true

resources:
  Resources:
    # Lambda Alias for stable version
    PingLambdaAliasLive:
      Type: AWS::Lambda::Alias
      Properties:
        FunctionName: !Ref PingLambdaFunction
        FunctionVersion: $LATEST
        Name: Live
        Description: Stable version for canary deployments
        
    # Lambda Alias for canary version  
    PingLambdaAliasCanary:
      Type: AWS::Lambda::Alias  
      Properties:
        FunctionName: !Ref PingLambdaFunction
        FunctionVersion: $LATEST
        Name: Canary
        Description: Canary version for testing

    # CloudWatch Alarms for monitoring
    PingErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: !Sub '${self:service}-${self:provider.stage}-ping-errors'
        AlarmDescription: Lambda function errors
        ComparisonOperator: GreaterThanThreshold
        EvaluationPeriods: 2
        MetricName: Errors
        Namespace: AWS/Lambda
        Period: 60
        Statistic: Sum
        Threshold: 0
        Dimensions:
          - Name: FunctionName
            Value: !Ref PingLambdaFunction

    PingLatencyAlarm:
      Type: AWS::CloudWatch::Alarm  
      Properties:
        AlarmName: !Sub '${self:service}-${self:provider.stage}-ping-latency'
        AlarmDescription: Lambda function latency
        ComparisonOperator: GreaterThanThreshold
        EvaluationPeriods: 2
        MetricName: Duration
        Namespace: AWS/Lambda
        Period: 60
        Statistic: Average
        Threshold: 1000
        Dimensions:
          - Name: FunctionName
            Value: !Ref PingLambdaFunction